### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by mikhail-shishov** [VeliovGroup/Meteor-Files-Demos#10]
- [x] Intcrease the space below "Upload via" sign
- [x] Make radio buttons look neater
- [x] Lighten the link color
- [x] Add the 2nd font
- [x] Change the "go back" icon
- [x] Change FontAwesome icons to Linear Icons
- [x] Store all used fonts under `/public/fonts` directory, avoid Google Fonts CDN
- [x] Add animation on upload button
- [x] Add hover color on Meteor and ostr.io icons
- [x] Add cancel button for stuck drag-n-grop

**Comment by dr-dimitru** [comment]
First part delivered in #11

**Comment by dr-dimitru** [comment]
Second part delivered in #12

**Comment by dr-dimitru** [comment]
Done few days ago. - https://twitter.com/smart_egg/status/971170946856947713
![mar-07-2018 02-44-35](https://user-images.githubusercontent.com/1686778/37423545-ce15632c-27c6-11e8-862b-ccc02cdde570.gif)
